config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pharmacies
  resources :prescriptions, only: [:index, :show]
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  belongs_to :pharmacy

  enum status: { pending: 0, preparation: 1, done: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :phone_number, presence: true
  has_many :chatrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit

  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # Uncomment when you *really understand* Pundit!
  # # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # # def user_not_authorized
  # #   flash[:alert] = "You are not authorized to perform this action."
  # #   redirect_to(root_path)
  # # end

  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      # redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show"
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  def index
    @pharmacies = Pharmacy.all
      @markers = @pharmacies.geocoded.map do |pharmacy|
      {
        lat: pharmacy.latitude,
        lng: pharmacy.longitude,
        info_window: render_to_string(partial: "info_window", locals: { pharmacy: pharmacy }),
        marker: render_to_string(partial: "marker", locals: { pharmacy: pharmacy }) }
      end
  end

  def show
  end

  def new
    @pharmacy = Pharmacy.new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
    @pharmacy = Pharmacy.find(params[:id])
    @pharmacy.destroy
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<div class="container">
  <div class="chatrooms">
    <% @chatrooms.each do |room| %>
      <%= link_to "#{room.chatroom_name}", chatroom_path(room.user_id), class:"chatroom-link" %>
    <% end %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div
  class="chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
  <div class="container">
  <h1><%= @chatroom.user.name %></h1>

  <div class="messages">
    <% @chatroom.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.name %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.message %></p>
      </div>
    <% end %>


  <%= simple_form_for [@chatroom, @message],
    remote: true,
    html: {class: "d-flex"} do |f|
  %>
    <%= f.input :message,
      label: false,
      placeholder: "ここに入力",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-success" %>
  <% end %>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

  </head>

  <body>
    <%= render "shared/topbar" %>
      <%= yield %>
    <%= render "shared/navbar" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1><%= Date.today %></h1>
</div>

app/views/pharmacies/_info_window.html.erb
<div class="pharmacy-card">
  <h2><%= pharmacy.pharmacy_name %></h2>
  <p><%= pharmacy.address %></p>
</div>

app/views/pharmacies/_marker.html.erb
<div class="marker" data-pharmacy-id="<%= pharmacy.id %>">
  <p><strong><%= pharmacy.address %></strong></p>
</div>
<i class="fas fa-caret-down"></i>

app/views/pharmacies/index.html.erb
<div class="container">
  <%# <%= render "shared/search_bar" %>
  <%= render "shared/map" %>
</div>

app/views/prescriptions/index.html.erb
<h1> Hello from prescription index</h1>

app/views/shared/_map.html.erb
<div class="mt-2">
  <div
      id="map"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      style='width: 100%; height: 82vh;' >
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-bottom">
  <div class="navbar-content">
    <ul class="navbar-list">
  <%# if user_signed_in? %>
      <li class="nav-item">
        <%= link_to root_path ,class: "nav-link" do %>
          <i class="fas fa-home"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to pharmacies_path, class: "nav-link" do %>
          <i class="fas fa-search"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to chatrooms_path, class: "nav-link" do %>
          <i class="fas fa-comment-alt"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "prescriptions", class: "nav-link" do %>
          <i class="fas fa-pills"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class: "nav-link" do %>
          <i class="fas fa-user-circle"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i>
      </button>
    </div>
  <% end %>

app/views/shared/_topbar.html.erb
<div class="topbar-lewagon">
</div>

app/views/users/index.html.erb
hello from users/index

app/views/users/show.html.erb
hello from users/show